// Fill out your copyright notice in the Description page of Project Settings.


#include "MapActor/BossMap_Actor.h"

ABossMap_Actor::ABossMap_Actor()
{	
	bHasPlayed = false; 
	
}

void ABossMap_Actor::Interact_Implementation(AActor* Interactor)
{
	if (!SkeletalMesh)
	{
		return;
	}

	ABossMap_Actor* Trigger = Cast<ABossMap_Actor>(Interactor);

	// 1. ÏµúÏ¥à Ìä∏Î¶¨Í±∞: Ïï†ÎãàÎ©îÏù¥ÏÖò Ïû¨ÏÉù ÏöîÏ≤≠ (BPÏóêÏÑú Ï≤òÎ¶¨)
	if (!bHasPlayed)
	{
		bHasPlayed = true;

		
		SkeletalMesh->SetPlayRate(CurrentPlayRate);

		UE_LOG(LogTemp, Warning, TEXT("‚ñ∂ ÏµúÏ¥à Ìä∏Î¶¨Í±∞, Ïï†ÎãàÎ©îÏù¥ÏÖò Ïû¨ÏÉù ÏãúÏûë (ÏÜçÎèÑ: %f)"), CurrentPlayRate);
	}
	// 2. Ïù¥ÌõÑ Ìä∏Î¶¨Í±∞: ÏÜçÎèÑÎßå Ï¶ùÍ∞Ä
	else if (Trigger && Trigger->MultiplyRate > 0.f)
	{
		CurrentPlayRate *= Trigger->MultiplyRate;
		SkeletalMesh->SetPlayRate(CurrentPlayRate);

		UE_LOG(LogTemp, Warning, TEXT("‚ñ∂ ÏÜçÎèÑ Ï¶ùÍ∞Ä! ÌòÑÏû¨ ÏÜçÎèÑ: %f"), CurrentPlayRate);
	}
}

void ABossMap_Actor::BeginPlay()
{
	Super::BeginPlay();
	for (AActor* Target : TargetActors)
	{
		if (Target)
		{
			UE_LOG(LogTemp, Warning, TEXT("üîπ TargetActor: %s"), *Target->GetName());
		}
	}
}

void ABossMap_Actor::OnTriggerBegin(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor,
	UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult)
{
	if (!OtherActor || OtherActor == this)
	{
		return;
	}
	if (AlreadyTriggeredActors.Contains(OtherActor))
	{
		return;
	}
	AlreadyTriggeredActors.Add(OtherActor);

	UE_LOG(LogTemp, Warning, TEXT("üî• OnTriggerBegin called ONCE by: %s"), *OtherActor->GetName());


	for (AActor* Target : TargetActors)
	{
		if (Target && Target->GetClass()->ImplementsInterface(UBase_Interface::StaticClass()))
		{
			IBase_Interface::Execute_Interact(Target, this); // ‚Üê selfÎ•º InteractorÎ°ú ÎÑòÍπÄ
		}
	}
	 
}

void ABossMap_Actor::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);
}
